package org.bank.security;

import java.io.Serializable;

import java.util.Date;

import java.util.HashMap;

import java.util.Map;

import java.util.function.Function;

import org.bank.model.User;
import org.bank.model.CustomUserDetails;
import org.bank.controller.AuthenticationController;
import io.jsonwebtoken.impl.DefaultClaims;
import org.springframework.beans.factory.annotation.Value;

import org.springframework.security.core.userdetails.UserDetails;

import org.springframework.stereotype.Component;

import io.jsonwebtoken.Claims;

import io.jsonwebtoken.Jwts;

import io.jsonwebtoken.SignatureAlgorithm;

@Component
public class TokenUtility implements Serializable {

    private static final long serialVersionUID = -2550185165626007488L;
    public static final long JWT_TOKEN_VALIDITY = 5 * 60 * 60;
    @Value("${jwt.secret}")
    private String secret;

    //retrieve username from jwt token
    public String getUsernameFromToken(String token) {
        return getClaimFromToken(token, Claims::getSubject);
    }

    //retrieve expiration date from jwt token
    public Date getExpirationDateFromToken(String token) {
        return getClaimFromToken(token, Claims::getExpiration);
    }



    public <T> T getClaimFromToken(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = getAllClaimsFromToken(token);
        Claims temp = claims;
        DefaultClaims s;
        return claimsResolver.apply(claims);
    }

    /**
     * Cuts the authorization request header and gets the token then query the token to JWTs to retrieve the userId
     * @param authorizationHeader the "Authorization" header as recieve from the controller
     * @return the userId retrieved
     * @throws ClassNotFoundException
     */
    public int getUserIdFromHeader(String authorizationHeader) throws ClassNotFoundException {
        String token = authorizationHeader.substring(7);
        return (int) getUserIdFromToken(token);
    }

    /**
     * Retrieves the id of the user from the jwt, that was generated by the method
     * {@link #generateToken(CustomUserDetails)}
     * @param token provided by the api to retrieve the userId stored in the jwt from the database
     * @return userId retrieved from the jwt
     */
    public Object getUserIdFromToken(String token) throws ClassNotFoundException {
        Claims claims = getAllClaimsFromToken(token);
        Object id = claims.get("id");
        if (id == null) {
            throw new ClassNotFoundException("Token is valid but does not store any id");
        }
        return id;
    }

    //for retrieving any information from token we will need the secret key
    private Claims getAllClaimsFromToken(String token) {
        return Jwts.parser().setSigningKey(secret).parseClaimsJws(token).getBody();
    }

    //check if the token has expired
    private Boolean isTokenExpired(String token) {
        final Date expiration = getExpirationDateFromToken(token);
        return expiration.before(new Date());
    }

    /**
     * Generates the token with the id in the payload
     * called by {@link AuthenticationController#login(User)} <br>
     * Id retrieval by {@link #getUserIdFromToken(String)} <br>
     * see {@link CustomUserDetails} <br>
     * @param userDetails
     * @return the token
     */
    public String generateToken(CustomUserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        // add the
        claims.put("id", userDetails.getId());
        return doGenerateToken(claims, userDetails.getUsername());
    }

    //while creating the token -
    //1. Define  claims of the token, like Issuer, Expiration, Subject, and the ID
    //2. Sign the JWT using the HS512 algorithm and secret key.
    //3. According to JWS Compact Serialization(https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-3.1)
    //   compaction of the JWT to a URL-safe string
    private String doGenerateToken(Map<String, Object> claims, String subject) {
        return Jwts.builder().setClaims(claims).setSubject(subject).setIssuedAt(new Date(System.currentTimeMillis()))
                .setExpiration(new Date(System.currentTimeMillis() + JWT_TOKEN_VALIDITY * 1000))
                .signWith(SignatureAlgorithm.HS512, secret).compact();
    }

    //validate token
    public Boolean validateToken(String token, CustomUserDetails userDetails) {
        final String username = getUsernameFromToken(token);
        return (username.equals(userDetails.getUsername()) && !isTokenExpired(token) && !userDetails.isLoggedOut());
    }
}